apiVersion: apps/v1
kind: Deployment
metadata:
  name: dumbkv
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dumbkv
  strategy:
    type: Recreate   # Ensures only one pod runs at a time
  template:
    metadata:
      labels:
        app: dumbkv
    spec:
      terminationGracePeriodSeconds: 5
      containers:
        - name: dumbkv
          image: ghcr.io/urvishkapadiya/srechallenge:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          env:
            - name: DATABASE_TYPE
              value: sqlite
            - name: DATABASE_LOCATION
              value: /data/dumbkvstore/db.sqlite3
          volumeMounts:
            - name: dumbkv-pvc
              mountPath: /data/dumbkvstore
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 20
      volumes:
        - name: dumbkv-pvc
          persistentVolumeClaim:
            claimName: dumbkv-pvc