apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - postgres-deployment.yaml
  - postgres-service.yaml
  - postgres-pvc.yaml
  - postgres-secret.yaml
  - postgres-config.yaml

# Patch dumbkv deployment to use Postgres
patches:
  - target:
      kind: Deployment
      name: dumbkv
    patch: |
      - op: replace
        path: /spec/template/spec/containers/0/env
        value:
          - name: DATABASE_TYPE
            valueFrom:
              configMapKeyRef:
                name: postgres-config
                key: DATABASE_TYPE
          - name: DATABASE_LOCATION
            valueFrom:
              configMapKeyRef:
                name: postgres-config
                key: DATABASE_LOCATION
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: postgres-secret
                key: POSTGRES_USER
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres-secret
                key: POSTGRES_PASSWORD