apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: dumbkv-servicemonitor
  namespace: default
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: dumbkv
  namespaceSelector:
    matchNames:
      - default
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
      scrapeTimeout: 10s
  sampleLimit: 10000
