name: PostgreSQL Unit Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  postgres-tests:
    name: Run Postgres Tests
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        options: >-
          --health-cmd "pg_isready -U postgres -d postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout Code
        uses: actions/checkout@v5

      - name: Setup Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      
      - name: Install uv
        run: curl -LsSf https://astral.sh/uv/install.sh | sh

      - name: Add uv to PATH
        run: echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Install Project Dependencies
        run: uv sync --locked --no-dev

      - name: Wait for Postgres Ready
        run: |
          for i in {1..10}; do
            pg_isready -h localhost -U postgres -d postgres && break
            echo "Waiting for Postgres to start..."
            sleep 2
          done

      - name: Run Postgres Tests
        run: uv run python -m pytest -v --database-location=postgres://postgres:postgres@localhost/postgres