name: SQLite Unit Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  sqlite-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install uv
        run: curl -LsSf https://astral.sh/uv/install.sh | sh

      - name: Add uv to PATH
        run: echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: uv sync --locked --no-dev

      - name: Run tests
        run: uv run python -m pytest -v